import bcrypt from 'bcryptjs';

const data = {
    users: [
        {
          name: 'Adrian',
          email: 'admin@example.com',
          password: bcrypt.hashSync('1234', 8),
          isAdmin: true,
        },
        {
          name: 'John',
          email: 'user@example.com',
          password: bcrypt.hashSync('1234', 8),
          isAdmin: false,
        },
      ],
    products: [
        {
            name: 'Nike Slim Shirt',
            category: 'Shirt',
            image: '/images/p1.jpg',
            price: 120,
            countInStock: 10,
            brand: 'Nike',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
            latitude: 33.8136,
            longitude: 151.0034,
        },
        {
            name: 'Nike Fit Shirt',
            category: 'Shirt',
            image: '/images/p2.jpg',
            price: 100,
            countInStock: 20,
            brand: 'Nike',
            rating: 4.0,
            numReviews: 10,
            description: 'high quality product',
            latitude: 33.8136,
            longitude: 151.0034,
        },
        {
            name: 'Nike Slim Pants',
            category: 'Pants',
            image: '/images/p3.jpg',
            price: 220,
            countInStock: 20,
            brand: 'Nike',
            rating: 5.0,
            numReviews: 12,
            description: 'high quality product',
            latitude: 33.8136,
            longitude: 151.0034,
        },
        {
            name: 'Nike Pants',
            category: 'Pants',
            image: '/images/p4.jpg',
            price: 25,
            countInStock: 5,
            brand: 'Nike',
            rating: 4.0,
            numReviews: 10,
            description: 'high quality product',
            latitude: 33.8136,
            longitude: 151.0034,
        },
        {
            name: 'Nike Slim tee',
            category: 'Shirt',
            image: '/images/p5.jpg',
            price: 220,
            countInStock: 15,
            brand: 'Nike',
            rating: 3.5,
            numReviews: 10,
            description: 'high quality product',
            latitude: 33.8136,
            longitude: 151.0034,
        },
        {
            name: 'Adidas Slim Shirt',
            category: 'Shirt',
            image: '/images/p6.jpg',
            price: 227,
            countInStock: 0,
            brand: 'Adidas',
            rating: 4.5,
            numReviews: 15,
            description: 'high quality product',
            latitude: 33.8136,
            longitude: 151.0034,
        },
    ],
};
export default data;
