const data = {
    product: [
        {
            _id: '1',
            name: 'Nike Slim Shirt',
            category: 'Shirt',
            image: '/images/p1.jpg',
            price: 120,
            brand: 'Nike',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id: '2',
            name: 'Nike Fit Shirt',
            category: 'Shirt',
            image: '/images/p2.jpg',
            price: 100,
            brand: 'Nike',
            rating: 4.0,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id: '3',
            name: 'Nike Slim Pants',
            category: 'Pants',
            image: '/images/p3.jpg',
            price: 220,
            brand: 'Nike',
            rating: 5.0,
            numReviews: 12,
            description: 'high quality product',
        },
        {
            _id: '4',
            name: 'Nike Pants',
            category: 'Pants',
            image: '/images/p4.jpg',
            price: 25,
            brand: 'Nike',
            rating: 4.0,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id: '5',
            name: 'Nike Slim Shirt',
            category: 'Shirt',
            image: '/images/p5.jpg',
            price: 220,
            brand: 'Nike',
            rating: 3.5,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id: '6',
            name: 'Adidas Slim Shirt',
            category: 'Shirt',
            image: '/images/p6.jpg',
            price: 227,
            brand: 'Adidas',
            rating: 4.5,
            numReviews: 15,
            description: 'high quality product',
        },
    ],
};
export default data;
